<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../Payment.Domain/Payment.Domain.csproj" /><ProjectReference Include="../Payment.Contracts/Payment.Contracts.csproj" /><ProjectReference Include="../../Ordering/Ordering.Contracts/Ordering.Contracts.csproj" /><ProjectReference Include="../../../BuildingBlocks/Commerce.BuildingBlocks.Application/Commerce.BuildingBlocks.Application.csproj" /></ItemGroup></Project>
