<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../../../BuildingBlocks/Commerce.BuildingBlocks.Contracts/Commerce.BuildingBlocks.Contracts.csproj" /><PackageReference Include="Google.Protobuf" Version="3.35.1" /><PackageReference Include="Grpc.Core.Api" Version="2.80.0" /><PackageReference Include="Grpc.Tools" Version="2.81.1" PrivateAssets="all" /><Protobuf Include="Protos/**/*.proto" GrpcServices="Both" ProtoRoot="Protos" /></ItemGroup></Project>
