<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../Cart.Contracts/Cart.Contracts.csproj" /><ProjectReference Include="../../../BuildingBlocks/Commerce.BuildingBlocks.Application/Commerce.BuildingBlocks.Application.csproj" /></ItemGroup></Project>
